config/routes.rb
Nested::Application.routes.draw do
  resources :cats do
    resources :fleas
  end
end

app/models/cat.rb
class Cat
  include Mongoid::Document

  field :name, type: String
  field :color, type: String

  embeds_many :fleas
end

app/models/flea.rb
class Flea
  include Mongoid::Document

  field :itchiness, type: Integer

  embedded_in :cat
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
  end

  def show
    @cat = Cat.find(params[:id])
  end
end 

app/controllers/fleas_controller.rb
 class FleasController < ApplicationController
  # before refactoring:
  # def index
  #   @cat = Cat.find params[:cat_id]
  #   @fleas = @cat.fleas
  # end

  # def show
  #   cat = Cat.find params[:cat_id]
  #   @flea = cat.fleas.find(params[:id])
  # end

  # after refactoring
  before_action :load_cat

  def index
  end

  def show
    @flea = @cat.fleas.find(params[:id])
  end

  private

  def load_cat
    @cat = Cat.find params[:cat_id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cats/index.html.erb
<h1>List of kitties</h1>

<% @cats.each do |cat| %>
  <p>
    ID: <%= link_to cat._id, cat_path(cat) %><br />
    Name: <%= cat.name %><br />
    Color: <%= cat.color %>
  </p>
<% end %>

app/views/cats/show.html.erb
<h1>Kittie <%= @cat._id %></h1>

<p>
  Name: <%= @cat.name %><br />
  Color: <%= @cat.color %><br />
  <%= link_to "Fleas", cat_fleas_path(@cat) %>
</p>

app/views/fleas/index.html.erb
<h1>List of fleas for cat <%= @cat.name %></h1>

<% @cat.fleas.each do |flea| %>
  <p>
    Itch factor: <%= flea.itchiness %><br>
    <%= link_to "Flea detail", cat_flea_path(@cat, flea) %>
  </p>
<% end %>

app/views/fleas/show.html.erb
<h1>Info for flea <%= @flea._id %></h1>

<p>The flea is this itchy: <%= @flea.itchiness %></p>
<p>The flea belongs to: <%= @flea.cat.name %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nested</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>